version: '3.8'

services:
  directus:
    image: directus/directus:11
    ports:
      - 8055:8055
    volumes:
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
      - ./templates:/directus/templates
      - ./certs:/certs:ro
    environment:
      KEY: ${KEY}
      SECRET: ${SECRET}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      DB_CLIENT: pg
      DB_CONNECTION_STRING: ${DB_CONNECTION_STRING}
      WEBSOCKETS_ENABLED: ${WEBSOCKETS_ENABLED}
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8055/admin/login"]
      interval: 5s
      timeout: 20s
      retries: 10

volumes:
  uploads:
  extensions:
  templates:
