version: '3.8'

services:
  directus:
    image: directus/directus:11
    ports:
      - 8055:8055
    volumes:
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
      - ./templates:/directus/templates
    environment:
      KEY: ${KEY}
      SECRET: ${SECRET}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      DB_CLIENT: pg
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_SSL__CA: |
        -----BEGIN CERTIFICATE-----
        MIIEQTCCAqmgAwIBAgIUH9rxYzyIRdgt3xtcsW4UY4ufltUwDQYJKoZIhvcNAQEM
        BQAwOjE4MDYGA1UEAwwvOGQ4NzJiYWQtMmY1Mi00OGZhLWFmZmQtYmQ0MDVkYzVm
        ZjA4IFByb2plY3QgQ0EwHhcNMjQxMTE1MDAxMDA1WhcNMzQxMTEzMDAxMDA1WjA6
        MTgwNgYDVQQDDC84ZDg3MmJhZC0yZjUyLTQ4ZmEtYWZmZC1iZDQwNWRjNWZmMDgg
        UHJvamVjdCBDQTCCAaIwDQYJKoZIhvcNAQEBBQADggGPADCCAYoCggGBAMaLaajj
        aHMmOab1aOOh1R07+bd6lJfZmbEa3YIdP2d9kQtGrM6p98itWGnhaXaub/TpoBGd
        ZUhnN5a+ZERBGRAd0tOkGM5UChaChYH4Ut7QL6y62ezE/kaYhsMYFzHR56Iw4SGN
        NMLE/Akk8+BSZilAwmWRIgZxlR6jtRoTH59XkWkcHNBtqT4v8uOIHXTUKqovROpp
        SJcu982xwhTD42dv9gJQvn1QxiButJwLldhQgUZuNLEK8QRn+1GDiy0snhuWUvGE
        3R5YB1N6+bl7QyhHKfWGK8MKpWmvHFeClSA9PfxjwiWjnaPccDdosVIXs0+/tz6e
        jfUSB7/Nzx1B6NFGXd7uqysatUtefR6uhE9DCX0ZJx6rKH6jIuJTKNfHE3qR6EpO
        Q10xJzMsA5fnUFb6DAkHc3WIi0edMJcPvfTKP+fMtep4ScRW/dH8q78/qxOg2xLb
        r7j5Ge4Jv5yUoCqVjgoIpnHFguEse1L92LXt0Bq8FXqNHq49fEMu6YgyjQIDAQAB
        oz8wPTAdBgNVHQ4EFgQUtH6LnbzMujP/wo51kcKtVu8DozYwDwYDVR0TBAgwBgEB
        /wIBADALBgNVHQ8EBAMCAQYwDQYJKoZIhvcNAQEMBQADggGBAKeD9PXBRIS3afDr
        /7yXi3vsXZilKQON3DmgiQXQlug+4LfVoBuuWNa7RK33U3LBCPrpez61AiS0lFQg
        JAAzh9wgwc6ZRj59TLJP4inaCej11EWkq9TXHwsXbmFKe+3P8jB5y0pyxUzsUOw6
        UBAIh9BMrWgs0khDaO/hAtiOCQgWkNBV7NBlGOPXAlSGrzbn8gnay8zJN5kLNp3+
        rnz2RbQsUKB79TsR5WbbDYdnbLHgzzcrWHshxe7qhrq7TtxrNXdl5TjXAER4iQbp
        jBaSkkJBFniGmHYRHfND18gEWCg4QlYQXgC3iufleQlElY6WjfT5MboyeBkMCs37
        ViyudITSNs4Tct/4T/dWTIMW4oWQxakUcjg3bQnCEgg7+MjTSC+rgV0XVqvGSAER
        lxI6iGpTKyqaDMmP3dMbFAAVpD96aRVv/zqGzQeVL3BRSnFZojazhXlBPBsgm+fL
        z3ut8DfX3K8HumhG6jYiAjhI36AdxWOzj75AZvQBY8QNMBB8VQ==
        -----END CERTIFICATE-----
      WEBSOCKETS_ENABLED: "true"
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8055/admin/login"]
      interval: 5s
      timeout: 20s
      retries: 10

volumes:
  uploads:
  extensions:
  templates:
